services:
  postgres:
    image: postgres:latest
    container_name: postgres_dev
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - postgresdb-data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis_dev
    ports:
      - 6379:6379
    volumes: 
      - cache:/data

volumes:
  postgresdb-data:
  cache: 
    driver: local
        
